import streamlit as st
import requests
import os
import tomllib

# --- CONFIGURATION & SETUP ---
st.set_page_config(page_title="DocMail AI", page_icon="🩺", layout="centered")

def get_api_url() -> str:
    """
    Determines the correct backend API endpoint URL based on the environment.
    Reads from Streamlit Secrets in production or a local config.toml for development.
    """
    # 1. Production: Check Streamlit Secrets
    if "BACKEND_URL" in st.secrets:
        backend_url = st.secrets["BACKEND_URL"]
        # Safety: Remove trailing slash if present to avoid double-slash errors
        if backend_url.endswith("/"):
            backend_url = backend_url[:-1]
        return f"{backend_url}/generate"

    # 2. Development: Fallback to local config
    try:
        # Check root first, then relative path
        config_path = "config.toml" if os.path.exists("config.toml") else "config/config.toml"
        
        with open(config_path, "rb") as f:
            config = tomllib.load(f)
        
        # Default to localhost if config is missing keys
        backend_url = config.get("api", {}).get("backend_url", "http://127.0.0.1:8000")
        return f"{backend_url}/generate"
        
    except FileNotFoundError:
        # Ultimate fallback
        return "http://127.0.0.1:8000/generate"

# Initialize URL
API_URL = get_api_url()

# --- SIDEBAR: SETTINGS ---
with st.sidebar:
    st.image("https://img.icons8.com/color/96/doctor-male--v1.png", width=80)
    st.title("Settings")
    
    st.markdown("### 🧠 AI Model Source")
    model_choice = st.radio(
        "Choose your Physician:",
        ("Fine-Tuned Llama 3 (RunPod)", "Claude 4.5 Sonnet (AWS Bedrock)"),
        index=0,
        help="Switch between the specialized local model (RunPod) and the generic cloud model (AWS)."
    )
    
    # Map selection to API parameter
    # "runpod" matches the check in backend/main.py
    api_source = "runpod" if "RunPod" in model_choice else "bedrock"
    
    st.divider()
    st.info(f"**Backend:** `{api_source.upper()}`")
    st.caption(f"Target: {API_URL}")

# --- MAIN UI ---
st.title("🩺 DocMail AI Assistant")
st.markdown("""
**Patient Triage & Response System**  
*Enter a patient message below to generate a clinically appropriate draft response.*
""")

# Input Area
email_input = st.text_area(
    "Patient Message:", 
    height=150, 
    placeholder="Doctor, I missed my dose of Metoprolol this morning. Should I double up now? It is 2pm."
)

# Action Button
if st.button("Generate Draft Response", type="primary"):
    if not email_input:
        st.warning("⚠️ Please enter a patient message to proceed.")
    else:
        # Dynamic Spinner Text
        spinner_text = "Consulting the Specialist (RunPod GPU)..." if api_source == "runpod" else "Consulting General Medicine (AWS Bedrock)..."
        
        with st.spinner(spinner_text):
            try:
                # 1. Construct Payload with the Model Switch
                payload = {
                    "patient_email": email_input,
                    "model_source": api_source  # <--- The New Switch
                }
                
                # 2. Call Backend
                response = requests.post(API_URL, json=payload, timeout=90)
                
                if response.status_code == 200:
                    data = response.json()
                    draft = data.get("draft_reply", "No text returned.")
                    sources = data.get("source_nodes", ["Unknown Source"])
                    
                    # 3. Display Result
                    st.subheader("Draft Reply")
                    st.text_area("Review & Edit:", value=draft, height=350)
                    
                    # 4. Source Analysis (RAG/Model Info)
                    with st.expander("🔍 Source Analysis & Logic", expanded=True):
                        st.markdown(f"**Generated by:** `{sources[0]}`")
                        if len(sources) > 1:
                            st.markdown("**Reference Context:**")
                            for src in sources[1:]:
                                st.markdown(f"- {src}")
                                
                else:
                    st.error(f"**Server Error:** {response.status_code}")
                    st.code(response.text)

            except requests.exceptions.ConnectionError:
                st.error("❌ Could not connect to the Backend. Is the Docker Container running?")
            except requests.exceptions.Timeout:
                st.error("⏳ Request Timed Out. The GPU might be cold-starting. Please try again.")
            except Exception as e:
                st.error(f"An unexpected error occurred: {e}")

# Footer
st.markdown("---")
st.caption("© 2026 SRF Development | DocMail MVP | Powered by Unsloth & AWS App Runner")
